upstream redblue{
        server 127.0.0.1:8081;
        server 127.0.0.1:8082;
    }

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location /google {
        return 301 https://www.google.com;
    }

 
    location /redblue{
        proxy_pass http://redblue/;
        # Запрещаем браузеру сохранять эту страницу в кэш
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";

	    # Гарантируем, что прокси не будет кэшировать ответы бэкендов
        proxy_buffering off;
    }

    location /music {
        root /usr/share/nginx/html;
        autoindex on;
    }

    location /pictures {
        root /usr/share/nginx/html;
        autoindex on;   
    }
}

server {
    listen 8081;
    location / {
        root /usr/share/nginx/html/red;
        index index.html;

    }
}

server {
    listen 8082;
    location / {
        root /usr/share/nginx/html/blue;
        index index.html;

    }
}


