apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
spec:
  resources:
    requests:
      storage: {{ .Values.pvcStorage}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  

